"use client";

import { useState } from "react";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowLeft,
  faKey,
  faCopy,
  faTrash,
} from "@fortawesome/free-solid-svg-icons";

export default function PasswordGeneratorPage() {
  const [length, setLength] = useState(12);
  const [password, setPassword] = useState("");

  const generatePassword = () => {
    const chars =
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+[]{}|;:,.<>?";
    let result = "";
    for (let i = 0; i < length; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    setPassword(result);
  };

  const handleCopy = () => {
    if (!password) return;
    navigator.clipboard.writeText(password);
    alert("Password copied to clipboard!");
  };

  const handleClear = () => {
    setPassword("");
  };

  return (
    <main className="w-full min-h-screen px-6 py-10">
      {/* Back Link */}
      <Link
        href="/"
        className="inline-flex items-center text-sm text-[#66AF85] hover:underline mb-6"
      >
        <FontAwesomeIcon icon={faArrowLeft} className="mr-2" />
        Back to Tools
      </Link>

      {/* Header */}
      <h1 className="text-3xl font-bold mb-2 flex items-center gap-2 text-gray-800">
        <FontAwesomeIcon icon={faKey} />
        Password Generator
      </h1>
      <p className="text-gray-600 mb-6">
        Generate secure random passwords quickly.
      </p>

      {/* Password Display */}
      <div className="flex gap-3 mb-4">
        <input
          type="text"
          value={password}
          readOnly
          placeholder="Your password will appear here"
          className="flex-1 border rounded-lg p-3 font-mono text-sm focus:ring-2 focus:ring-[#66AF85] outline-none"
        />
        <button
          onClick={handleCopy}
          className="bg-[#66AF85] text-white px-4 py-2 rounded hover:bg-[#589c71] flex items-center gap-2"
        >
          <FontAwesomeIcon icon={faCopy} /> Copy
        </button>
      </div>

      {/* Length Selector & Buttons */}
      <div className="flex gap-3 items-center mb-6">
        <label className="flex flex-col text-sm">
          Length
          <input
            type="number"
            min={6}
            max={64}
            value={length}
            onChange={(e) => setLength(parseInt(e.target.value) || 12)}
            className="border rounded px-2 py-1 mt-1 w-24"
          />
        </label>
        <button
          onClick={generatePassword}
          className="bg-[#66AF85] text-white px-4 py-2 rounded hover:bg-[#589c71]"
        >
          Generate
        </button>
        <button
          onClick={handleClear}
          className="bg-gray-300 text-gray-700 px-4 py-2 rounded hover:bg-gray-400 flex items-center gap-2"
        >
          <FontAwesomeIcon icon={faTrash} /> Clear
        </button>
      </div>
      <section className="rich-content text-gray-700 mt-16 pt-8 border-t border-gray-200 max-w-4xl mx-auto">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">
          Why Use a Random Password Generator?
        </h2>
        <p className="mb-4">
          In today's digital landscape, a strong, unique password is your first
          and most critical line of defense against cyber threats. Using a
          **random password generator** ensures that your credentials are not
          based on dictionary words, personal information (like birth dates or
          names), or simple patterns, making them virtually impossible for
          hackers and brute-force programs to guess. This tool uses a robust
          algorithm based on a wide set of characters to deliver passwords with
          high cryptographic entropy.
        </p>

        <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-6">
          Security and Best Practices
        </h3>
        <p className="mb-4">
          We strongly recommend passwords of **12 characters or more**,
          incorporating a mix of **uppercase letters, lowercase letters,
          numbers, and symbols**. While longer passwords are technically more
          secure, modern security standards typically prioritize the
          **unpredictability** generated by true randomness. All password
          generation in this tool is performed **client-side** (in your
          browser), meaning the passwords generated are never transmitted over
          the internet or logged by our servers, guaranteeing your privacy.
        </p>

        <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-6">
          Tips for Managing Strong Passwords
        </h3>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li>
            **Use a Password Manager:** Never rely on your memory. Store
            generated passwords securely using tools like Google Password
            Manager, LastPass, or 1Password.
          </li>
          <li>
            **Unique for Every Account:** Use a different randomly generated
            password for every single online service to prevent a breach on one
            site from compromising all your accounts.
          </li>
          <li>
            **Enable Two-Factor Authentication (2FA):** For your most critical
            accounts (email, banking), use 2FA as an essential secondary defense
            layer.
          </li>
        </ul>
      </section>
    </main>
  );
}
