// app/privacy-policy/page.js
export default function PrivacyPolicyPage() {
  return (
    <main className="px-6 py-10 max-w-4xl mx-auto text-gray-700">
      <h1 className="text-3xl font-bold text-gray-800 mb-6 border-b pb-2">
        Privacy Policy for HJ Tools Hub
      </h1>

      <p className="mb-4">
        This Privacy Policy describes how [Your Company Name/Site Name]
        collects, uses, and discloses your Personal Information when you visit
        or make a purchase from the Site.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800 mb-3 mt-6">
        Information We Collect
      </h2>
      <p className="mb-4">
        **For Tools:** Our tools process files entirely in your browser or are
        immediately deleted from our servers after the process is complete. We
        do not store your files.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800 mb-3 mt-6">
        Third-Party Services (Google Ads)
      </h2>
      <p className="mb-4">
        We use Google AdSense/Google Ads to serve advertisements on our site.
        Google uses cookies to serve ads based on a user's prior visits to your
        website or other websites. You can read more about how Google uses your
        Personal Information here: [Link to Google's Privacy & Terms page].
      </p>

      {/* Add more sections: Consent, Your Rights, Changes, Contact Info */}
      <p className="mt-8 font-medium">
        **IMPORTANT:** Replace this placeholder text with professional,
        comprehensive, and legally compliant content generated by a legal
        service or professional.
      </p>
    </main>
  );
}
