// app/terms/page.js
export default function TermsOfUsePage() {
  return (
    <main className="px-6 py-10 max-w-4xl mx-auto text-gray-700">
      <h1 className="text-3xl font-bold text-gray-800 mb-6 border-b pb-2">
        Terms of Use for HJ Tools Hub
      </h1>

      <p className="mb-4">
        Welcome to HJ Tools Hub. By accessing or using our website, you agree to
        be bound by these Terms of Use.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800 mb-3 mt-6">
        Acceptable Use
      </h2>
      <p className="mb-4">
        You agree not to use our tools for any unlawful purpose or to violate
        any national or international laws. Our tools are provided for personal,
        non-commercial use only.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800 mb-3 mt-6">
        Disclaimer
      </h2>
      <p className="mb-4">
        The tools are provided "as is" without any warranties. We do not
        guarantee that the service will be uninterrupted or error-free.
      </p>

      {/* Add more sections: Intellectual Property, Termination, Governing Law */}
      <p className="mt-8 font-medium">
        **IMPORTANT:** Replace this placeholder text with professional,
        comprehensive, and legally compliant content generated by a legal
        service or professional.
      </p>
    </main>
  );
}
